
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = FPS * 5
PLAYER_SPEED = FPS * 3.3
PLAYER_SHOOT_SPEED = 8.3 * FPS
PLAYER_SHOOT_COOLDOWN = .3

SHOT_RADIUS = 5
